### ISSUE TITLE
implement templating engine

### ISSUE THREAD

**Issue by spielhoelle** [devugees/dci-express-api#30]

**Comment by afuh** [comment]
I did a layout and couple of templates. I also updated several stuff in order to make a basic relationship and be able to see and interact with them. I didn't test anything yet.

**Comment by afuh** [comment]
All tests are passing now, but there are a few tests that are outdated (they are not testing for anything). Also, I realized that there is no User test (I set up a basic one)
Anyway, the templates are up and running.  ;)
